// Main/official tool URLs sourced from ai-toolbox-base-v4 my edit.xlsx, column "URL (main page)".
const toolUrls: Record<string, string> = {
  "10web": "https://10web.io/",
  airtable: "https://www.airtable.com/",
  base44: "https://base44.com/",
  bolt: "https://bolt.new/",
  botpress: "https://botpress.com/",
  canva: "https://www.canva.com/",
  capcut: "https://www.capcut.com/",
  chatgpt: "https://chatgpt.com/",
  claude: "https://claude.ai/",
  clickfunnels: "https://www.clickfunnels.com/",
  cloudflare: "https://www.cloudflare.com/",
  "co-pilot": "https://copilot.microsoft.com/",
  cursor: "https://cursor.com/",
  deepseek: "https://chat.deepseek.com/sign_in",
  dreamina: "https://dreamina.capcut.com",
  elevenlabs: "https://elevenlabs.io/",
  emergent: "https://emergent.sh/",
  fathom: "https://www.fathom.ai/",
  figma: "https://www.figma.com/",
  firebase: "https://firebase.google.com/",
  fireflies: "https://fireflies.ai/",
  "flux.2": "https://bfl.ai/models/flux-2",
  "framer ai": "https://www.framer.com/ai/",
  gamma: "https://gamma.app/",
  gemini: "https://gemini.google.com/",
  github: "https://github.com/",
  glm: "https://z.ai/",
  "google gemini": "https://gemini.google.com/",
  granola: "https://www.granola.ai/",
  grok: "https://grok.com/",
  "google ai studio": "https://aistudio.google.com/",
  "hailuo ai": "https://hailuoai.video/",
  heygen: "https://www.heygen.com/en-gb",
  "higgsfield ai": "https://higgsfield.ai/",
  hostinger: "https://www.hostinger.com/",
  ideogram: "https://ideogram.ai/",
  ithy: "https://ithy.com/",
  kimi: "https://www.kimi.com/",
  "kling ai": "https://kling.ai/",
  krea: "https://www.krea.ai/",
  lovable: "https://lovable.dev/",
  lovart: "https://www.lovart.ai",
  magnific: "https://www.magnific.com/",
  make: "https://www.make.com/en",
  manus: "https://manus.im/",
  manychat: "https://manychat.com/",
  midjourney: "https://www.midjourney.com/",
  minimax: "https://www.minimax.io/",
  mixo: "https://www.mixo.io/",
  n8n: "https://n8n.io/",
  "notebook lm": "https://notebooklm.google/",
  notion: "https://www.notion.com/",
  obsidian: "https://obsidian.md/",
  "openrouter": "https://openrouter.ai/",
  "otter.ai": "https://otter.ai/",
  perplexity: "https://www.perplexity.ai/",
  picsart: "https://picsart.com/",
  pickaxe: "https://pickaxe.co/",
  pika: "https://pika.art/",
  pinecone: "https://www.pinecone.io/",
  posthog: "https://posthog.com/",
  qwen: "https://qwen.ai/",
  replit: "https://replit.com/",
  resend: "https://resend.com/",
  runway: "https://runway.com/",
  slack: "https://slack.com/",
  soundraw: "https://soundraw.io/",
  suno: "https://suno.com/",
  supabase: "https://supabase.com/",
  "systeme.io": "https://systeme.io/",
  systeme: "https://systeme.io/",
  tactiq: "https://tactiq.io/",
  udio: "https://www.udio.com/",
  v0: "https://v0.app/",
  "veo 3": "https://www-veo3.com/",
  vercel: "https://vercel.com/",
  "wan ai": "https://wan.video/",
  windsurf: "https://windsurf.com/enterprise/account/login",
  wordpress: "https://wordpress.com/",
  xmind: "https://xmind.com/",
  zapier: "https://zapier.com/",
};

export function toolUrlForName(toolName: string) {
  return toolUrls[toolName.trim().toLowerCase()] ?? "";
}

export default toolUrls;
